name: CI/CD Pipeline

on:
  push:
    branches: [ main, cpp_version ]
  pull_request:
    branches: [ main, cpp_version ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: fileservice_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          libjsoncpp-dev \
          uuid-dev \
          zlib1g-dev \
          openssl \
          libssl-dev \
          postgresql-server-dev-all \
          libpq-dev

    - name: Install Drogon
      run: |
        git clone https://github.com/drogonframework/drogon
        cd drogon
        git submodule update --init
        mkdir build && cd build
        cmake ..
        make -j$(nproc)
        sudo make install

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_TESTING=ON ..

    - name: Build
      run: |
        cd build
        make -j$(nproc)

    - name: Run Tests
      run: |
        cd build
        ctest --output-on-failure

  docker:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/fileservice:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/fileservice:${{ github.sha }}
        cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/fileservice:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/fileservice:buildcache,mode=max

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Deploy to Production
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/fileservice:${{ github.sha }}
          docker stop fileservice || true
          docker rm fileservice || true
          docker run -d \
            --name fileservice \
            --restart always \
            -p 3000:3000 \
            -v /data/fileservice:/app/storage \
            --env-file /etc/fileservice/.env \
            ${{ secrets.DOCKERHUB_USERNAME }}/fileservice:${{ github.sha }}
